### ISSUE TITLE
Can't start on Windows: no XLib found

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#31]
The XLib method of polling mouse position doesn't work on Windows, so that PyVMEC now doesn't start when I try it on Windows. When creating the mouse polling object, it should pick the best one, but gracefully degrade to the PsychoPy method if there is no XLib available. In this case: use a try - except statement that first tries to create the XLib-based object, and if there is an exception, create a PsychoPy-based object that behaves exactly the same way.

https://docs.python.org/2/tutorial/errors.html

**Comment by juliusjgm12** [comment]
I think it should work now but i don't have a Windows machine to try it on

**Comment by thartbm** [comment]
Will try on my virtual box.

**Comment by thartbm** [comment]
Oh... it's not synched to github yet... that's why I still get the same error. Can you sync asap?
